ola_djnago/blog/urls.py
from blog import views
from django.urls import path

app_name = 'blog'

# blog/
urlpatterns = [
    path('', views.blog, name='home'),
    path('<int:post_id>/', views.post, name='post'),
    path('exemplo/', views.exemplo, name='exemplo'),
]

ola_djnago/blog/models.py
from django.db import models

# Create your models here.

ola_djnago/blog/views.py
from blog.data import posts
from django.http import  Http404, HttpRequest
from django.shortcuts import render
from typing import Any



def blog(request):
    print('blog')

    context = {
        # 'text': 'Olá blog',
        'posts': posts
    }

    return render(
        request,
        'blog/index.html',
        context
    )


def post(request: HttpRequest, post_id: int):
    found_post: dict[str, Any] | None = None


    for post in posts:
        if post['id'] == post_id:
            found_post = post   
            break

    if found_post is None:
        raise Http404('Post não existe.')

            

    context = {
        # 'text': 'Olá blog',
        'post': found_post,
        'title': found_post['title'] + ' - ',
    }

    return render(
        request,
        'blog/post.html',
        context
    )


def exemplo(request):
    print('exemplo')

    context = {
        'text': 'Olá exemplo',
        'title': 'Essa é uma página de exemplo - ',
    }

    return render(
        request,
        'blog/exemplo.html',
        context
    )

ola_djnago/blog/templates/blog/exemplo.html
{% extends 'global/base.html' %}

{% block texto %} {{ text }} {% endblock texto %}

ola_djnago/blog/templates/blog/index.html
{% extends 'global/base.html' %}

{% block texto %} {{ text }} {% endblock texto %}

{% block posts %}
  {% for post in posts %}
    {% include 'global/partials/postblock.html' %}
  {% endfor %}
{% endblock posts %}

ola_djnago/blog/templates/blog/post.html
{% extends 'global/base.html' %}

{% block texto %} {{ text }} {% endblock texto %}

{% block posts %}
<article class="post single-post">
    <header>
        <h1 class="post__title"> 
            <a href="{% url "blog:post" post.id %}">
                {{ post.title }}
            </a>
        </h2>
    </header>
    <div class="post__body">{{ post.body }} </div>
</article>  
{% endblock posts %}